### PR TITLE
Various edits

### PR DESCRIPTION
**Pull request by jpmckinney**
(Getting late to describe changes. Maybe tomorrow.)

In addition to changes listed by @ColinMaudry below:

Schema

* Put fields under a `secondStage` object, in case we add future fields to describe the second stage
* Rename properties to use 'Candidates' instead of 'Tenderers' to avoid confusion with parties in first stage
* Remove `envisagedNumberTenderers` and instead set min/max to same number to express an exact limit
* Remove `envisagedNumberTenderersRationale` as this will need to go on a selection criteria extension for eForms

### CODE REVIEW

**Review by ColinMaudry — APPROVED** [review]
Great job! I was shy to extend existing extensions, so I stuck to add properties to the core objects. From now on I'll be bolder.

**Comment by ColinMaudry** [comment]
Changes:

- renamed the extension to ocds_candidateLimit_extension
- the extension extends the `Lots` object instead of the `Tender` object
- added the required sections to the README (guidance, legal context, example, issues)

**Comment by ColinMaudry** [comment]
@jpmckinney On a second thought, what did you replace `tender.envisagedNumberTenderers` with?

Also, what if the procedure is not divided in lots? It's a single `Lot`?

**Comment by jpmckinney** [comment]
> what did you replace tender.envisagedNumberTenderers with?

In eForms, they put this on BT-750 (Selection Criteria Description), since those criteria will be used to select the limited number. I therefore used the readme to explain the use of `eligibilityCriteria` (the perhaps confusing equivalent of selection criteria in OCDS).

**Update:** Sorry, misread the field name. That's replaced by guidance in the readme to set mix/max to the same number. I should probably add the guidance to the field descriptions. (Done now.)

**Comment by jpmckinney** [comment]
> Also, what if the procedure is not divided in lots? It's a single Lot?

See https://github.com/open-contracting-extensions/european-union/issues/36, in which case there is always a single 'virtual' lot.

**Comment by jpmckinney** [comment]
Regarding my earlier comment about `tender.eligibilityCriteria`: I forgot that we can't use that as information is per lot. We'll need a selection criteria extension (matching eForms).

**Pull request merged**
